* Library Information
 - Filename :: [[file:gnus-summary-ext.el][gnus-summary-ext.el]]
 - Description :: Extra limit and process mark commands for the gnus summary buffer
 - Author :: Joe Bloggs <vapniks@yahoo.com>
 - Maintainer :: Joe Bloggs <vapniks@yahoo.com>
Copyleft (Ↄ) 2013, Joe Bloggs, all rites reversed.
 - Created :: 2013-12-23 00:06:16
 - Version :: 0.1
 - Last-Updated :: 2013-12-23 00:06:16
 -           By :: Joe Bloggs
 - URL :: https://github.com/vapniks/gnus-summary-ext
 - Keywords :: comm
 - Compatibility :: GNU Emacs 24.3.1
 - Package-Requires :: ((macro-utils "1.0"))

* Possible Dependencies

gnus, macro-utils, cl

* Commentary
Bitcoin donations gratefully accepted :: 16mhw12vvtzCwQyvvLAqCSBvf8i41CfKhK

This library provides extra limit commands for filtering the gnus summary buffer,
some commands for performing actions on MIME parts in articles,
and some general functions for evaluating elisp code in all articles that have the
process mark. See the documentation of the individual commands & functions for more
details.

* Commands
-  `gnus-summary-ext-limit-to-mime-type'
    Limit the summary buffer to articles containing MIME parts with types matching REGEX.
    Keybinding: M-x gnus-summary-ext-limit-to-mime-type
-  `gnus-summary-ext-apply-to-marked-safely'
    Call function FN for all articles that are process/prefixed.
    Keybinding: M-x gnus-summary-ext-apply-to-marked-safely
-  `gnus-summary-ext-apply-to-marked'
    Evaluate any lisp expression for all articles that are process/prefixed.
    Keybinding: M-x gnus-summary-ext-apply-to-marked
-  `gnus-summary-ext-limit-to-num-parts'
    Limit the summary buffer to articles containing between MIN & MAX attachments.
    Keybinding: M-x gnus-summary-ext-limit-to-num-parts
-  `gnus-summary-ext-limit-to-size'
    Limit the summary buffer to articles of size between MIN and MAX bytes.
    Keybinding: M-x gnus-summary-ext-limit-to-size
-  `gnus-summary-ext-limit-to-filename'
    Limit the summary buffer to articles containing attachments with names matching REGEX.
    Keybinding: M-x gnus-summary-ext-limit-to-filename
-  `gnus-summary-ext-mime-actions-on-parts'
    Perform ACTIONS on all MIME parts in the current buffer. 
    Keybinding: M-x gnus-summary-ext-mime-actions-on-parts
-  `gnus-summary-ext-act-on-parts-in-marked'
    Do something with all MIME parts in articles that are process/prefixed.
    Keybinding: M-x gnus-summary-ext-act-on-parts-in-marked
-  `gnus-summary-ext-limit-filter'
    Limit the summary buffer to articles which match EXPR.
    Keybinding: M-x gnus-summary-ext-limit-filter
-  `gnus-summary-ext-uu-mark-filter'
    Apply/remove process mark to all articles in the summary buffer which match EXPR.
    Keybinding: M-x gnus-summary-ext-uu-mark-filter
-  `gnus-summary-ext-extract-text'
    Extract text from process marked articles.
* Options
-  `gnus-summary-ext-saved-filters'
    A list of named filters that can be used with `gnus-summary-ext-limit-filter'.
    default = nil
-  `gnus-summary-ext-mime-actions'
    A list of sets of actions to apply to different mime types.
    default = nil
* Installation

 - If you have [[http://www.marmalade-repo.org/][marmalade-repo.org]], this gnus-summary-ext is part of the emacs packages you can install.  
   Just type M-x package-install gnus-summary-ext marmalade 
 - Otherwise download the library from here Lisp:gnus-summary-ext, and put it in a directory in the emacs load path, 
   like ~/.emacs.d
 - Add (require 'gnus-summary-ext) in your ~/.emacs file
